const NodeType = Object.freeze({
  Variable: "Variable",
  LiteralNumber: "LiteralNumber",
  LiteralFloat: "LiteralFloat",
  LiteralString: "LiteralString",
  LiteralBoolean: "LiteralBoolean",
  LiteralUnit: "LiteralUnit",
  Abstraction: "Abstraction",
  AbstractionParameter: "AbstractionParameter",
  Application: "Application",
  TypedExpression: "TypedExpression",
  Export: "Export",
  NameExport: "NameExport",
  Extern: "Extern",
  Assignment: "Assignment",
  Access: "Access",
  If: "If",
  Where: "Where",
  Pattern: "Pattern",
  Is: "Is",
  Do: "Do",
  Placeholder: "Placeholder",
  TemplateString: "TemplateString",
  TupleConstructor: "TupleConstructor",
  ListConstructor: "ListConstructor",
  Record: "Record",
  JSExpression: "JSExpression",
  ADT: "ADT",
  Constructor: "Constructor",
});

module.exports = {
  NodeType,
};
