const NodeType = Object.freeze({
  Variable: "Variable",
  LiteralNumber: "LiteralNumber",
  LiteralString: "LiteralString",
  LiteralBoolean: "LiteralBoolean",
  LiteralUnit: "LiteralUnit",
  Abstraction: "Abstraction",
  AbstractionParameter: "AbstractionParameter",
  Application: "Application",
  TypedExpression: "TypedExpression",
  Export: "Export",
  Assignment: "Assignment",
  FieldAccess: "FieldAccess",
  If: "If",
  Where: "Where",
  Pattern: "Pattern",
  Is: "Is",
  NamespaceAccess: "NamespaceAccess",
  Placeholder: "Placeholder",
  TemplateString: "TemplateString",
  TupleConstructor: "TupleConstructor",
  ListConstructor: "ListConstructor",
  Record: "Record",
  JSExpression: "JSExpression",
  ADT: "ADT",
  Constructor: "Constructor",
});

module.exports = {
  NodeType,
};
